/**
 * Brainfuck Challenges — 45 problems, all unlocked after tutorial
 */
const CHALLENGES = [
  // ═══ EASY — Cell operations first ═══
  { id: 'cell-sum', title: 'Cell Sum', difficulty: 'Easy', category: 'Cell Math',
    description: 'Input is "()". Read both chars. Add their ASCII values: 40 + 41 = 81. Output the character for 81: "Q".',
    examples: [{ input: '()', output: 'Q' }],
    constraints: ['Input: exactly "()".', 'Output the ASCII char of the sum.'],
    hints: ['(=40 )=41. Sum = 81 = Q. Read both, add them, output the result.'],
    defaultCode: '', testCases: [{ input: '()', expectedOutput: 'Q' }], order: 1 },

  { id: 'cell-sub', title: 'Cell Subtraction', difficulty: 'Easy', category: 'Cell Math',
    description: 'Input is ") (". Read both chars. Subtract: 41 - 40 = 1. Output the digit "1".',
    examples: [{ input: ') (', output: '1' }],
    constraints: ['Input: exactly ") (".', 'Output: ASCII digit of the result.'],
    hints: [')=41 (=40. Subtract 41-40=1. Output as ASCII (1+48=49="1").'],
    defaultCode: '', testCases: [{ input: ') (', expectedOutput: '1' }], order: 2 },

  { id: 'cell-mul', title: 'Cell Multiplication', difficulty: 'Easy', category: 'Cell Math',
    description: 'Input is "*+". Multiply ASCII values: 42 × 43 = 1806 mod 256 = 14. Output byte 14.',
    examples: [{ input: '*+', output: '\x0e' }],
    constraints: ['Input: exactly "*+".', 'Output: the byte result (mod 256).'],
    hints: ['*=42 +=43. 42×43=1806→mod 256=14. Repeat addition in a loop.'],
    defaultCode: '', testCases: [{ input: '*+', expectedOutput: String.fromCharCode(14) }], order: 3 },

  { id: 'abc-repeat', title: 'ABC × 5', difficulty: 'Easy', category: 'Loops',
    description: 'Print "ABCABCABCABCABC" (ABC repeated 5 times).',
    examples: [{ input: '', output: 'ABCABCABCABCABC' }],
    constraints: ['No input.'],
    hints: ['A=65 B=66 C=67. Loop 5 times.'],
    defaultCode: '', testCases: [{ input: '', expectedOutput: 'ABCABCABCABCABC' }], order: 4 },

  { id: 'hello-world', title: 'Hello, World!', difficulty: 'Easy', category: 'Strings',
    description: 'Print "Hello World!" (without quotes).',
    examples: [{ input: '', output: 'Hello World!' }],
    constraints: ['No input.'],
    hints: ['H=72 e=101 l=108 o=111 W=87 r=114 d=100 !=33 space=32'],
    defaultCode: '', testCases: [{ input: '', expectedOutput: 'Hello World!' }], order: 5 },

  { id: 'cat-echo', title: 'Echo', difficulty: 'Easy', category: 'I/O',
    description: 'Read 3 characters and print them back unchanged.',
    examples: [{ input: 'abc', output: 'abc' }],
    constraints: ['Input: 3 chars.'],
    hints: ['Read (,) then print (.) three times.'],
    defaultCode: '', testCases: [{ input: 'abc', expectedOutput: 'abc' }, { input: 'xyz', expectedOutput: 'xyz' }], order: 6 },

  { id: 'uppercase', title: 'To Uppercase', difficulty: 'Easy', category: 'Strings',
    description: 'Read a lowercase letter and output its uppercase version.',
    examples: [{ input: 'a', output: 'A' }],
    constraints: ['Input: one lowercase a-z.'],
    hints: ['Lowercase - 32 = Uppercase.'],
    defaultCode: '', testCases: [{ input: 'a', expectedOutput: 'A' }, { input: 'm', expectedOutput: 'M' }, { input: 'z', expectedOutput: 'Z' }], order: 7 },

  { id: 'print-ab', title: 'Print AB', difficulty: 'Easy', category: 'Output',
    description: 'Print the string "AB".',
    examples: [{ input: '', output: 'AB' }],
    hints: ['A=65 B=66.'],
    defaultCode: '', testCases: [{ input: '', expectedOutput: 'AB' }], order: 8 },

  { id: 'lowercase', title: 'To Lowercase', difficulty: 'Easy', category: 'Strings',
    description: 'Read an uppercase letter and output its lowercase version.',
    examples: [{ input: 'A', output: 'a' }],
    constraints: ['Input: one uppercase A-Z.'],
    hints: ['Uppercase + 32 = Lowercase.'],
    defaultCode: '', testCases: [{ input: 'A', expectedOutput: 'a' }, { input: 'H', expectedOutput: 'h' }, { input: 'Z', expectedOutput: 'z' }], order: 9 },

  { id: 'print-alphabet', title: 'Alphabet', difficulty: 'Easy', category: 'Loops',
    description: 'Print lowercase a-z: "abcdefghijklmnopqrstuvwxyz".',
    examples: [{ input: '', output: 'abcdefghijklmnopqrstuvwxyz' }],
    hints: ["Start at 97 ('a'). Loop 26 times."],
    defaultCode: '', testCases: [{ input: '', expectedOutput: 'abcdefghijklmnopqrstuvwxyz' }], order: 10 },

  { id: 'print-z-to-a', title: 'Reverse Alphabet', difficulty: 'Easy', category: 'Loops',
    description: 'Print uppercase Z to A backwards: "ZYXWVUTSRQPONMLKJIHGFEDCBA".',
    examples: [{ input: '', output: 'ZYXWVUTSRQPONMLKJIHGFEDCBA' }],
    hints: ['Z=90. Loop 26 times: print, decrement.'],
    defaultCode: '', testCases: [{ input: '', expectedOutput: 'ZYXWVUTSRQPONMLKJIHGFEDCBA' }], order: 11 },

  { id: 'negate', title: 'Negate a Digit', difficulty: 'Easy', category: 'Math',
    description: 'Read a digit n (0-9). Output the digit (9-n). "0"→"9", "4"→"5", "9"→"0".',
    examples: [{ input: '0', output: '9' }, { input: '4', output: '5' }],
    constraints: ['Input: one digit 0-9.'],
    hints: ['9-n: Read n, store it, set 9 (ASCII 57), subtract n, output result.'],
    defaultCode: '', testCases: [{ input: '0', expectedOutput: '9' }, { input: '5', expectedOutput: '4' }, { input: '9', expectedOutput: '0' }], order: 12 },

  { id: 'swap-case', title: 'Swap Case', difficulty: 'Easy', category: 'Strings',
    description: 'Read a letter. If lowercase, output uppercase. If uppercase, output lowercase.',
    examples: [{ input: 'a', output: 'A' }, { input: 'H', output: 'h' }],
    constraints: ['Input: one letter A-Z or a-z.'],
    hints: ['If ASCII ≥ 97 (lowercase): subtract 32. Otherwise: add 32. Use branching.'],
    defaultCode: '', testCases: [{ input: 'a', expectedOutput: 'A' }, { input: 'H', expectedOutput: 'h' }, { input: 'z', expectedOutput: 'Z' }, { input: 'M', expectedOutput: 'm' }], order: 13 },

  { id: 'digit-avg', title: 'Average of Two', difficulty: 'Easy', category: 'Math',
    description: 'Read two digits a,b. Output (a+b)/2 rounded down as digit. "48"→"6", "37"→"5".',
    examples: [{ input: '48', output: '6' }, { input: '37', output: '5' }],
    constraints: ['Input: 2 chars 0-9.', 'Output: single digit.'],
    hints: ['Add both values, then divide by 2 (halve them by subtracting 2 repeatedly).'],
    defaultCode: '', testCases: [{ input: '48', expectedOutput: '6' }, { input: '37', expectedOutput: '5' }, { input: '22', expectedOutput: '2' }, { input: '99', expectedOutput: '9' }], order: 14 },

  { id: 'triangle-star', title: 'Right Triangle', difficulty: 'Easy', category: 'Patterns',
    description: 'Print a right triangle of asterisks, 5 lines: "*\\n**\\n***\\n****\\n*****".',
    examples: [{ input: '', output: '*\n**\n***\n****\n*****' }],
    hints: ['*=42, newline=10. Loop i from 1 to 5: inner loop prints i stars, then newline.'],
    defaultCode: '', testCases: [{ input: '', expectedOutput: '*\n**\n***\n****\n*****' }], order: 15 },

  // ═══ MEDIUM ═══
  { id: 'add-two', title: 'Add Two Digits', difficulty: 'Medium', category: 'Math',
    description: 'Read two digits (0-9) and output sum. "34"→"7". Sum is 0-9.',
    examples: [{ input: '34', output: '7' }],
    constraints: ['Input: 2 chars 0-9.', 'Sum single digit.'],
    hints: ["'0'=48. Subtract 48 from each, add, add 48 back."],
    defaultCode: '', testCases: [{ input: '34', expectedOutput: '7' }, { input: '81', expectedOutput: '9' }], order: 16 },

  { id: 'sub-two', title: 'Subtract Digits', difficulty: 'Medium', category: 'Math',
    description: 'Read a,b. Output a-b. b ≤ a. "73"→"4".',
    examples: [{ input: '73', output: '4' }],
    constraints: ['b ≤ a.'],
    hints: ['Loop: decrement a b times.'],
    defaultCode: '', testCases: [{ input: '73', expectedOutput: '4' }, { input: '85', expectedOutput: '3' }], order: 17 },

  { id: 'greater-than', title: 'Which is Larger?', difficulty: 'Medium', category: 'Logic',
    description: 'Read two digits, output the larger one.',
    examples: [{ input: '37', output: '7' }],
    hints: ['Copy both. Subtract one from the other. Branch with [ ].'],
    defaultCode: '', testCases: [{ input: '19', expectedOutput: '9' }, { input: '63', expectedOutput: '6' }, { input: '44', expectedOutput: '4' }], order: 18 },

  { id: 'multiply-digits', title: 'Multiply Digits', difficulty: 'Medium', category: 'Math',
    description: 'Read two digits, output product. "23"→"6". Product 0-9.',
    examples: [{ input: '23', output: '6' }],
    constraints: ['Product single digit.'],
    hints: ['Multiplication = repeated addition.'],
    defaultCode: '', testCases: [{ input: '23', expectedOutput: '6' }, { input: '42', expectedOutput: '8' }], order: 19 },

  { id: 'count-a', title: "Count the A's", difficulty: 'Medium', category: 'Strings',
    description: "Read 8 lowercase chars. Count how many 'a' and output count.",
    examples: [{ input: 'abracada', output: '4' }],
    constraints: ['Input: exactly 8 chars.'],
    hints: ["'a'=97. For each: subtract 97, if zero increment counter."],
    defaultCode: '', testCases: [{ input: 'abracada', expectedOutput: '4' }, { input: 'zzzzzzzz', expectedOutput: '0' }], order: 20 },

  { id: 'double-it', title: 'Double It', difficulty: 'Medium', category: 'Math',
    description: 'Read n (0-4) and output n×2. "3"→"6".',
    examples: [{ input: '3', output: '6' }],
    constraints: ['n ≤ 4.'],
    hints: ['n×2 = n+n. Read, copy, add.'],
    defaultCode: '', testCases: [{ input: '0', expectedOutput: '0' }, { input: '2', expectedOutput: '4' }, { input: '4', expectedOutput: '8' }], order: 21 },

  { id: 'is-even', title: 'Is it Even?', difficulty: 'Medium', category: 'Logic',
    description: "Read digit 0-9. Output '1' if even, '0' if odd.",
    examples: [{ input: '4', output: '1' }],
    hints: ['Subtract 2 in loop. If you hit 0 → even.'],
    defaultCode: '', testCases: [{ input: '0', expectedOutput: '1' }, { input: '3', expectedOutput: '0' }, { input: '6', expectedOutput: '1' }], order: 22 },

  { id: 'square', title: 'Square It', difficulty: 'Medium', category: 'Math',
    description: 'Read n (0-3) and output n².',
    examples: [{ input: '3', output: '9' }],
    hints: ['n² = n×n. Loop n times, add n each iteration.'],
    defaultCode: '', testCases: [{ input: '0', expectedOutput: '0' }, { input: '2', expectedOutput: '4' }, { input: '3', expectedOutput: '9' }], order: 23 },

  { id: 'abs-diff', title: 'Absolute Difference', difficulty: 'Medium', category: 'Math',
    description: 'Read a,b, output |a-b|. "73"→"4", "37"→"4".',
    examples: [{ input: '73', output: '4' }],
    hints: ['Find larger first, then subtract smaller.'],
    defaultCode: '', testCases: [{ input: '73', expectedOutput: '4' }, { input: '37', expectedOutput: '4' }], order: 24 },

  { id: 'countdown', title: 'Countdown!', difficulty: 'Medium', category: 'Loops',
    description: 'Read digit n (1-9). Print digits from n down to 0. "5"→"543210".',
    examples: [{ input: '5', output: '543210' }],
    constraints: ['Input: one digit 1-9.'],
    hints: ['Convert ASCII to value. Loop: print as digit, decrement until 0, print 0.'],
    defaultCode: '', testCases: [{ input: '5', expectedOutput: '543210' }, { input: '3', expectedOutput: '3210' }, { input: '9', expectedOutput: '9876543210' }], order: 25 },

  { id: 'pyramid', title: 'Number Pyramid', difficulty: 'Medium', category: 'Patterns',
    description: 'Print: "1\\n12\\n123\\n1234\\n12345" (5-line number pyramid).',
    examples: [{ input: '', output: '1\n12\n123\n1234\n12345' }],
    hints: ['ASCII 1=49, newline=10. Outer loop 1..5, inner loop prints 1..i.'],
    defaultCode: '', testCases: [{ input: '', expectedOutput: '1\n12\n123\n1234\n12345' }], order: 26 },

  { id: 'max-of-3', title: 'Maximum of Three', difficulty: 'Medium', category: 'Logic',
    description: 'Read 3 digits (0-9), output the maximum one. "374"→"7".',
    examples: [{ input: '374', output: '7' }],
    constraints: ['Input: 3 chars 0-9.'],
    hints: ['Compare a vs b to get max(a,b), then compare that with c.'],
    defaultCode: '', testCases: [{ input: '374', expectedOutput: '7' }, { input: '281', expectedOutput: '8' }, { input: '555', expectedOutput: '5' }], order: 27 },

  { id: 'min-of-3', title: 'Minimum of Three', difficulty: 'Medium', category: 'Logic',
    description: 'Read 3 digits, output the minimum. "374"→"3".',
    examples: [{ input: '374', output: '3' }],
    constraints: ['Input: 3 chars 0-9.'],
    hints: ['Compare a vs b for min, then compare with c.'],
    defaultCode: '', testCases: [{ input: '374', expectedOutput: '3' }, { input: '281', expectedOutput: '1' }, { input: '555', expectedOutput: '5' }], order: 28 },

  { id: 'remove-vowels', title: 'Remove Vowels', difficulty: 'Medium', category: 'Strings',
    description: "Read 5 lowercase letters, output only consonants. 'hello'→'hll'.",
    examples: [{ input: 'hello', output: 'hll' }],
    constraints: ['Input: 5 lowercase.'],
    hints: ['Read each char. Check if vowel (a/e/i/o/u). Print only if not.'],
    defaultCode: '', testCases: [{ input: 'hello', expectedOutput: 'hll' }, { input: 'aeiou', expectedOutput: '' }, { input: 'brain', expectedOutput: 'brn' }], order: 29 },

  { id: 'zigzag', title: 'ZigZag Pattern', difficulty: 'Medium', category: 'Patterns',
    description: 'Print alternating pattern of 10 chars: "*#*#*#*#*#".',
    examples: [{ input: '', output: '*#*#*#*#*#' }],
    hints: ['*=42, #=35. Loop 5 times: print *, print #.'],
    defaultCode: '', testCases: [{ input: '', expectedOutput: '*#*#*#*#*#' }], order: 30 },

  { id: 'caesar-plus1', title: 'Caesar +1', difficulty: 'Medium', category: 'Crypto',
    description: 'Read a lowercase letter a-y and output the next letter. "a"→"b", "h"→"i", "y"→"z".',
    examples: [{ input: 'a', output: 'b' }, { input: 'y', output: 'z' }],
    constraints: ['Input: a-y (no z).'],
    hints: ['Simply add 1 to the ASCII value.'],
    defaultCode: '', testCases: [{ input: 'a', expectedOutput: 'b' }, { input: 'h', expectedOutput: 'i' }, { input: 'y', expectedOutput: 'z' }], order: 31 },

  { id: 'first-last', title: 'First & Last', difficulty: 'Medium', category: 'Strings',
    description: 'Read 4 letters. Output first and last only. "abcd"→"ad".',
    examples: [{ input: 'abcd', output: 'ad' }, { input: 'math', output: 'mh' }],
    constraints: ['Input: exactly 4 chars.'],
    hints: ['Read into cells 0-3, print cell 0, move to cell 3, print cell 3.'],
    defaultCode: '', testCases: [{ input: 'abcd', expectedOutput: 'ad' }, { input: 'code', expectedOutput: 'ce' }, { input: 'fizz', expectedOutput: 'fz' }], order: 32 },

  { id: 'times-table', title: 'Times Table of 3', difficulty: 'Medium', category: 'Math',
    description: 'Print 3×1 through 3×9: "369121518212427".',
    examples: [{ input: '', output: '369121518212427' }],
    hints: ['For i=1..9: print 3*i as number. 3*i mod 10 gives last digit; handle tens by separate digit cell. Or: just accumulate 3 each iteration and print two-digit number.'],
    defaultCode: '', testCases: [{ input: '', expectedOutput: '369121518212427' }], order: 33 },

  { id: 'bracket-check', title: 'Bracket Mirror', difficulty: 'Medium', category: 'Logic',
    description: 'Read "(" or ")". Output the matching bracket. "("→")", ")"→"(".',
    examples: [{ input: '(', output: ')' }, { input: ')', output: '(' }],
    constraints: ['Input: exactly "(" or ")".'],
    hints: ['(=40, )=41. If input=40: output 41. Else: output 40. Difference is 1.'],
    defaultCode: '', testCases: [{ input: '(', expectedOutput: ')' }, { input: ')', expectedOutput: '(' }], order: 34 },

  { id: 'digit-sum-3', title: 'Sum of Three', difficulty: 'Medium', category: 'Math',
    description: 'Read 3 digits. Output their sum mod 10 as digit. "123"→"6", "789"→"4".',
    examples: [{ input: '123', output: '6' }, { input: '789', output: '4' }],
    constraints: ['Input: 3 chars 0-9.', 'Output: single digit 0-9.'],
    hints: ['Add all three, take mod 10. Use repeated subtraction of 10 til <10.'],
    defaultCode: '', testCases: [{ input: '123', expectedOutput: '6' }, { input: '789', expectedOutput: '4' }, { input: '555', expectedOutput: '5' }], order: 35 },

  // ═══ HARD ═══
  { id: 'reverse-5', title: 'Reverse 5 Letters', difficulty: 'Hard', category: 'Strings',
    description: 'Read 5 lowercase, output reversed. "hello"→"olleh".',
    examples: [{ input: 'hello', output: 'olleh' }],
    constraints: ['Input: 5 lowercase.'],
    hints: ['Read into cells 0-4. Print 4→0 moving left.'],
    defaultCode: '', testCases: [{ input: 'hello', expectedOutput: 'olleh' }, { input: 'brain', expectedOutput: 'niarb' }], order: 36 },

  { id: 'is-vowel', title: 'Is it a Vowel?', difficulty: 'Hard', category: 'Logic',
    description: "Read lowercase letter. Output '1' if vowel, else '0'.",
    examples: [{ input: 'a', output: '1' }],
    hints: ['Compare against 97,101,105,111,117.'],
    defaultCode: '', testCases: [{ input: 'a', expectedOutput: '1' }, { input: 'b', expectedOutput: '0' }, { input: 'e', expectedOutput: '1' }, { input: 'z', expectedOutput: '0' }], order: 37 },

  { id: 'rot13', title: 'ROT13 Cipher', difficulty: 'Hard', category: 'Crypto',
    description: 'Read a-z. ROT13: a→n, n→a, z→m.',
    examples: [{ input: 'a', output: 'n' }],
    hints: ['If < 110: +13. Else: -13.'],
    defaultCode: '', testCases: [{ input: 'a', expectedOutput: 'n' }, { input: 'n', expectedOutput: 'a' }, { input: 'z', expectedOutput: 'm' }], order: 38 },

  { id: 'sort-3', title: 'Sort 3 Digits', difficulty: 'Hard', category: 'Algorithms',
    description: 'Read 3 digits, output sorted ascending. "312"→"123".',
    examples: [{ input: '312', output: '123' }],
    hints: ['Bubble sort: compare and swap adjacent pairs.'],
    defaultCode: '', testCases: [{ input: '312', expectedOutput: '123' }, { input: '978', expectedOutput: '789' }, { input: '555', expectedOutput: '555' }], order: 39 },

  { id: 'fibonacci', title: 'Fibonacci Digits', difficulty: 'Hard', category: 'Math',
    description: 'Print last digits of first 10 Fibonacci: 1123583145.',
    examples: [{ input: '', output: '1123583145' }],
    hints: ['Last digit mod 10. next = (prev+curr)%10.'],
    defaultCode: '', testCases: [{ input: '', expectedOutput: '1123583145' }], order: 40 },

  { id: 'to-binary', title: 'Digit to Binary', difficulty: 'Hard', category: 'Math',
    description: 'Read 0-9, output 4-bit binary. "5"→"0101".',
    examples: [{ input: '5', output: '0101' }],
    hints: ['Check ≥8→1, subtract 8. Repeat 4,2,1.'],
    defaultCode: '', testCases: [{ input: '5', expectedOutput: '0101' }, { input: '9', expectedOutput: '1001' }, { input: '0', expectedOutput: '0000' }], order: 41 },

  { id: 'gcd', title: 'GCD of Two', difficulty: 'Hard', category: 'Math',
    description: 'Read two digits a,b. Output gcd(a,b) as digit. "62"→"2", "84"→"4", "55"→"5".',
    examples: [{ input: '62', output: '2' }, { input: '84', output: '4' }],
    constraints: ['Input: 2 chars 0-9.', 'Output: single digit.'],
    hints: ['Euclidean algorithm: while b≠0: t=b, b=a mod b, a=t. Output a. Implement mod by repeated subtraction.'],
    defaultCode: '', testCases: [{ input: '62', expectedOutput: '2' }, { input: '84', expectedOutput: '4' }, { input: '55', expectedOutput: '5' }, { input: '93', expectedOutput: '3' }], order: 42 },

  { id: 'collatz-single', title: 'Collatz Steps', difficulty: 'Hard', category: 'Algorithms',
    description: 'Read n (1-9). Count Collatz steps to reach 1 and output count. n=6→8 steps, n=3→7 steps.',
    examples: [{ input: '6', output: '8' }, { input: '3', output: '7' }],
    constraints: ['Input: one digit 1-9.', 'Output: digit count of steps.'],
    hints: ['While n>1: if even→n/2, else→3n+1. Count steps. Output count.'],
    defaultCode: '', testCases: [{ input: '1', expectedOutput: '0' }, { input: '3', expectedOutput: '7' }, { input: '6', expectedOutput: '8' }], order: 43 },

  { id: 'diamond-3', title: 'Diamond Pattern', difficulty: 'Hard', category: 'Patterns',
    description: 'Print a 3-line diamond of asterisks: " *\\n***\\n *".',
    examples: [{ input: '', output: ' *\n***\n *' }],
    hints: ['space=32, *=42, newline=10. Row 1: space, star. Row 2: three stars. Row 3: space, star.'],
    defaultCode: '', testCases: [{ input: '', expectedOutput: ' *\n***\n *' }], order: 44 },

  { id: 'brainfuck-quine', title: 'Quine', difficulty: 'Hard', category: 'Advanced',
    description: 'Print your own source code! Output must match stripped BF source.',
    examples: [],
    constraints: ['No input.', 'Output = stripped source.'],
    hints: ['Encode source as ASCII values, print with loops. The ultimate challenge.'],
    defaultCode: '', testCases: [], order: 45 }
];

const DIFFICULTY_COLORS = { 'Easy': '#00b8a3', 'Medium': '#ffc01e', 'Hard': '#ff375f' };
